twig:
    file_name_pattern: "*.twig"
    paths:
        # point this wherever your css files live
        "%kernel.project_dir%/assets/styles": styles
when@test:
    twig:
        strict_variables: true
